spring.application.name=stram-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coderefine
spring.datasource.username=postgres
spring.datasource.password=Postgres@9124
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8000

# JWT
app.jwt.secret=coderefine_super_secret_key_2024_production_change_this
app.jwt.expiration-ms=86400000

# Groq AI
app.groq.api-key=${GROQ_API_KEY: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}
app.groq.model=llama-3.3-70b-versatile
app.groq.api-url=https://api.groq.com/openai/v1/chat/completions

# Actuator health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
